name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use the Python version compatible with your Lambda environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t package/  # Install dependencies into the 'package' directory

      - name: Package Lambda function
        run: |
          cp Data-code.py package/  # Copy the Python script to the 'package' directory
          cd package
          zip -r ../function.zip .  # Zip the content of the 'package' directory

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change to your desired AWS region

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name My-data-code --zip-file fileb://function.zip
